spring.application.name=catalog-service
server.port=8081

# Conexão com o Postgres que subimos no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/db_catalogo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Desativa a criação automática pelo Hibernate (pois usaremos o Flyway)
spring.jpa.hibernate.ddl-auto=validate