CREATE TABLE products (
                          id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name      VARCHAR(255)  NOT NULL,
                          price     NUMERIC(12,2) NOT NULL CHECK (price >= 0),
                          category  VARCHAR(80),
                          stock     INT           NOT NULL DEFAULT 0 CHECK (stock >= 0)
);