CREATE TABLE tb_product (
                            id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name      VARCHAR(255)  NOT NULL,
                            price     DOUBLE PRECISION NOT NULL CHECK (price > 0),
                            category  VARCHAR(255)  NOT NULL,
                            stock     INT           NOT NULL CHECK (stock > 0)
);